platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/twilio/cocoapod-specs'

target 'Crush' do
	use_frameworks!
        
		pod 'Firebase/Core'
        pod 'Firebase/Auth'
        pod 'PhoneVerificationController'
        pod 'FirebaseUI/Auth'
        pod 'Alamofire', '~> 4.7'

end
